# Generated by Django 4.1.2 on 2022-10-29 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0002_song_artiste_id_song_artistes_song_date_released_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lyric',
            name='content',
            field=models.CharField(default=1, max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lyric',
            name='song_artistes',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='song_artiste', to='musicapp.song'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lyric',
            name='song_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='musicapp.song'),
            preserve_default=False,
        ),
    ]
