# Generated by Django 4.1.2 on 2022-11-04 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0003_lyric_content_lyric_song_artistes_lyric_song_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='lyric',
            name='song_name',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
