# Generated by Django 4.1.2 on 2022-11-04 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0004_lyric_song_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lyric',
            name='song_artistes',
        ),
        migrations.RemoveField(
            model_name='song',
            name='artiste_id',
        ),
        migrations.RemoveField(
            model_name='song',
            name='artistes',
        ),
        migrations.AddField(
            model_name='song',
            name='artist_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='musicapp.artiste'),
            preserve_default=False,
        ),
    ]
