# Generated by Django 4.1.2 on 2022-11-05 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0006_alter_song_artist_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='artist_id',
        ),
        migrations.AddField(
            model_name='song',
            name='artiste_id',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='musicapp.artiste'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='artistes',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='artiste', to='musicapp.artiste'),
            preserve_default=False,
        ),
    ]
