# Generated by Django 4.1.2 on 2022-11-05 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0007_remove_song_artist_id_song_artiste_id_song_artistes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='artiste_id',
        ),
        migrations.RemoveField(
            model_name='song',
            name='artistes',
        ),
        migrations.AddField(
            model_name='song',
            name='artist_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='musicapp.artiste'),
        ),
    ]
