# Generated by Django 4.1.2 on 2022-11-05 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0008_remove_song_artiste_id_remove_song_artistes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lyric',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='lyric',
            name='song_name',
            field=models.TextField(),
        ),
    ]
