# Generated by Django 4.1.2 on 2022-11-06 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0009_alter_lyric_content_alter_lyric_song_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lyric',
            name='song_name',
        ),
        migrations.AlterField(
            model_name='lyric',
            name='song_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='musicapp.song'),
        ),
    ]
